import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class ProjectService {

  public mintCost = 2;
  public mintCurrency = 'SOL';
  public vips = [
    '../../assets/vips/01.png',
    '../../assets/vips/02.png',
    '../../assets/vips/03.png',
    '../../assets/vips/04.png',
    '../../assets/vips/05.png',
    '../../assets/vips/06.png',
    '../../assets/vips/07.png',
  ];

  public faqs = [
    {
      question: 'The Bones Club, what is it?',
      answer: `The Bones Club was, is and will be the private and trending club on the Solana blockchain.

      Join the club to relax with like-minded Skully Boys and projects in the metaverse.

      Participate in secret meetings about the future of the world, win NFTs or make contacts that may change your life.

      Membership in the Bones Club will give you access to exclusive benefits in the real world and in the Metaverse.

      Visits to the Club are free, but benefits will only be given to owners of the Skully Boys collection.
      Bones Club Forever!`
    },
    {
      question: `What are Skully Boys?`,
      answer: `SkullyBoys are a collection of 5555 unique NFT avatars chilling on the Solana blockchain. 

      Owning a Skully Boys grants you exclusive access to the Skully Boys Bones Club. 

      Each Skully Boys is algorithmically generated by randomly combining together numerous professionally designed properties across 9 categories.`
    },
    {
      question: `How can I become a member of the Skully Boys Bones Club?`,
      answer: `The only way to join the Skully Boys Bones Club is to own a Skully Boy.
      
      The 5555 Skully Boys NFT collection will be for sale on our website on the release date. `
    },
    {
      question: `How can I buy a Skully Boy?`,
      answer: `The launch date of the collection will be announced in few days.

      Skully Boys will be online at www.skullyboys.io.

      When the market will be sold out you will have to go to opensea.

      Skully Boys will be blind minted for 2 SOL`
    },
    {
      question: `How is the value of a Skully Boy estimated?`,
      answer: `At the launching, all Skully Boys have the same price.
      
      After the launch there is a high chance that the prices explode by the rarity of the traits.`
    },
    {
      question: `How can i get the @Skully Boys role on the discord?`,
      answer: `You need to have a Skully Boy in your wallet, and create a support ticket in the Skully Boys discord.`
    },
  ];
  public roadmapBoxes = [
    [`The Launch`, `Skully Boys will make their appearance at the launch of the website`],
    [`Awakening of the Skullys`, `5555 Skullys will be revealed ready to be minted on the Solana blockchain.`],
    [`VIP Club Incoming`, `Creation of the “VIP Skully Boys Bones Club”.`],
    [`The Audit`, `Listing on a Tools to check the items value.`],
    [`Skully Goodies`, `Launch of the Skully’Goodies available for the Skully Community.`],
    [`Skully Art Gallery`, `The Skully Boys will appear in an Art Gallery.`],
    [`Charity Skull`, `Creation of a Charity and The VIP Skully Bones Boys Club will decide where the donation will goes.`],
    [`Deadly Curses`, `The Curse hit another club, stay tuned to find out more.`],
    [`It's a Mystery, Gang!`, `Mystery Guest Collab for the promotion of Skully Community, it’s going to be huge!`],
    [`Skully Gang`, `New Project: New Skully XXXXX Project Announced, Gaming project loading..`],
    [`Skully Gang II`, `New Skully XXXXX Drop! New Features rise from the grave..`],
    [`Skully Gang III`, `Second Exhibition : Be ready for the mint, not for the small player, well-informed audience.`],
    [`Mystery`, `Mysterious Collection revealed, where the curse casts its spell ?`],
    [`The Vision`, `This is just the beginning of the Skully Epic, do not blink or you will miss something!`],
  ];

  public startTime = new BehaviorSubject(1632166860); // Monday, September 20, 2021 7:41:00 PM GMT
  constructor() { }
}
