import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-faq-page',
  templateUrl: './faq-page.component.html',
  styleUrls: ['./faq-page.component.scss']
})
export class FaqPageComponent implements OnInit {

  faqItems = [
    {
      question: 'The Bones Club, what is it?',
      answer: `The Bones Club was, is and will be the private and trending club on the Solana blockchain.
      Join the club to relax with like-minded Skully Boys and projects in the metaverse.
      Participate in secret meetings about the future of the world, win NFTs or make contacts that may change your life.
      Membership in the Bones Club will give you access to exclusive benefits in the real world and in the Metaverse.
      Visits to the Club are free, but benefits will only be given to owners of the Skully Boys collection.
      Bones Club Forever!`
    },
    {
      question: `What are Skully Boys?`,
      answer: `SkullyBoys are a collection of 5555 unique NFT avatars chilling on the Solana blockchain. 
      Owning a Skully Boys grants you exclusive access to the Skully Boys Bones Club. 
      Each Skully Boys is algorithmically generated by randomly combining together numerous professionally designed properties across 9 categories.`
    },
    {
      question: `How can I become a member of the Skully Boys Bones Club?`,
      answer: `The only way to join the Skully Boys Bones Club is to own a Skully Boy. The 5555 Skully Boys NFT collection will be for sale on our website on the release date. `
    },
    {
      question: `How can I buy a Skully Boy?`,
      answer: `The launch date of the collection will be announced in few days.
      Skully Boys will be online on www.skullyboys.io
      When the market will be sold out you will have to go to opensea.
      Skully Boys will be blind minted for 2 SOL`
    },
    {
      question: `How is the value of a Skully Boy estimated?`,
      answer: `At the launching, all Skully Boys have the same price but there is a high chance that the prices explode by the rarity of the traits.`
    },
    {
      question: `How can i get the @Skully Boys role on the discord?`,
      answer: `You need to have a Skully Boy in your wallet, and create a support ticket in the Skully Boys discord.`
    },
  ];

  constructor() { }

  ngOnInit(): void {
  }

}
